#!/bin/bash

# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo -ne "Bringing down the wireless interface..."
ifconfig wlan0 down
tput cuf $(($(tput cols)-48))
tput setaf 2
echo "[OK]     "
tput setaf 7
echo -ne "Changing interface back to managed networks..."
iwconfig wlan0 mode Managed
tput cuf $(($(tput cols)-55))
tput setaf 2
echo "[OK]     "
tput setaf 7
echo -ne "Starting NetworkManager..."
service network-manager start &> /dev/null
tput cuf $(($(tput cols)-35))
tput setaf 2
echo "[OK]     "
tput setaf 7
echo -ne "Restarting NetworkManager to reconnect..."
sleep 1
service network-manager restart &> /dev/null
tput cuf $(($(tput cols)-50))
tput setaf 2
echo "[OK]     "
tput setaf 7
echo "You are now being connected to normal wireless communications."
